name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-servee:latest ./todo-servee --push
        docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-client:latest ./todo-client --push

    - name: Deploy to Ubuntu
      run: |
        ssh root@134.209.211.176 "cd /path/to/your/repo && docker-compose up -d"
